/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int fibo[5000];

int fibonacci (int n) {
	if (fibo[n]) {
		return fibo[n];
	}
	fibo[n] = fibonacci(n-1)+fibonacci(n-2);
	return fibo[n];
}

int main () {
	fibo[0] = 1;
	fibo[1] = 1;
	int i,sum,n;
	for (i=0;(n=fibonacci(i))<4000000;i++) {
		if (!(n % 2)) {
			sum += n;
		}
	}
	printf ("%d\n",sum);
	return 0;
}


